service: serverless-authentication-test-token # NOTE: update this with your service name

provider:
  name: aws
  stage: dev
  region: us-east-1
  runtime: nodejs4.3

functions:
  testToken:
    handler: handler.test
    events:
      - http:
          path: test-token
          method: get
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: true
          authorizer:
            arn: arn:aws:lambda:us-east-1:957571668058:function:serverless-authentication-dev-authorize:14
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            identityValidationExpression: .*
